version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"  # or "daily" for more frequent checks
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "Alishba431"   # optional: assign yourself
