name: Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  BUILD_DIR: public
  DEPLOY_TARGET: github-pages   

permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build / Prepare
        run: |
          echo "🏗️ Building site..."
          node run.js || echo "⚠️ run.js exited with non-zero; continuing to gather artifacts"

      - name: Run tests
        run: npm test || echo "⚠️ Tests failed (continuing pipeline)"

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: public-site
          path: ${{ env.BUILD_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: public-site

      - name: Deploy to GitHub Pages
        if: env.DEPLOY_TARGET == 'github-pages'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Deploy to Heroku (optional)
        if: env.DEPLOY_TARGET == 'heroku'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          echo "🚀 Deploying to Heroku..."
          if [ -z "${HEROKU_API_KEY}" ] || [ -z "${HEROKU_APP_NAME}" ]; then
            echo "❌ Missing HEROKU_API_KEY or HEROKU_APP_NAME secrets — skipping deployment."
            exit 0
          fi
          git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git || true
          git add -f public
          git commit -m "chore: deploy public build [ci skip]" || true
          git push --force heroku HEAD:main
